# Generated by Django 4.2.2 on 2023-06-21 17:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="cover_photo",
            field=models.ImageField(
                blank=True,
                default="media/house_sample.jpg",
                null=True,
                upload_to="media",
                verbose_name="Main Photo",
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="photo1",
            field=models.ImageField(
                blank=True,
                default="media/interior_sample.jpg",
                null=True,
                upload_to="media",
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="photo2",
            field=models.ImageField(
                blank=True,
                default="media/interior_sample.jpg",
                null=True,
                upload_to="media",
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="photo3",
            field=models.ImageField(
                blank=True,
                default="media/interior_sample.jpg",
                null=True,
                upload_to="media",
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="photo4",
            field=models.ImageField(
                blank=True,
                default="media/interior_sample.jpg",
                null=True,
                upload_to="media",
            ),
        ),
    ]
