export const PROPERTY_LIST_REQUEST = "PROPERTY_LIST_REQUEST";
export const PROPERTY_LIST_SUCCESS = "PROPERTY_LIST_SUCCESS"; //SUCCESFUL REQUEST FOR LISTING PRODUCTS
export const PROPERTY_LIST_FAIL = "PROPERTY_LIST_FAIL";