# Generated by Django 4.2.2 on 2023-06-21 17:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0002_alter_profile_profile_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_photo",
            field=models.ImageField(
                default="media/profile_default.png",
                upload_to="media",
                verbose_name="Profile photo",
            ),
        ),
    ]
